name: Adams Studios Inc.
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5361
title: Adams Studios Inc.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#291612'
    - '#4c2d2a'
    - '#7e5a5e'
    - '#8d756b'
  brandStrength: 0.5140648663509637
  lightness: 0.6278690041508526
  saturation: 0.75
  rhythmicContrast: 0.5332182752899826
purpose: []
